### ISSUE TITLE
No module named 'multicrop'

### ISSUE THREAD

**Issue by caijinyue** [jeya-maria-jose/KiU-Net-pytorch#20]
(pytorch) caijinyue@titan:~/桌面/KiU-Net-pytorch-master/BRATS$ python train_kiunet.py 
Traceback (most recent call last):
  File "train_kiunet.py", line 19, in <module>
    from data import datasets
  File "/home/caijinyue/桌面/KiU-Net-pytorch-master/BRATS/data/datasets.py", line 1, in <module>
    from .dualpath import DualData, DualData25, DualData28
  File "/home/caijinyue/桌面/KiU-Net-pytorch-master/BRATS/data/dualpath.py", line 18, in <module>
    import multicrop
ModuleNotFoundError: No module named 'multicrop'

**Comment by jeya-maria-jose** [comment]
Please Install custom pytorch kernels from https://github.com/thuyen/multicrop
